### ISSUE TITLE
hexo error

### ISSUE THREAD

**Issue by wangweitung** [appotry/docker-hexo#18]
docker部署后，进入docker，运行hexo server报错如下：

![图片](https://github.com/appotry/docker-hexo/assets/8080125/aaec2d77-d9d1-4f5c-b0ee-f59476a1d45a)

**Comment by appotry** [comment]
删除node_modules目录，npm缓存也清理一下，重新安装npm环境试试。可能是你的环境问题

**Comment by wangweitung** [comment]
> 删除node_modules目录，npm缓存也清理一下，重新安装npm环境试试。可能是你的环境问题

谢谢提醒，我是docker部署。删除node_modules目录后，重新`sudo docker-compose up -d`提示

![图片](https://github.com/appotry/docker-hexo/assets/8080125/7afb74c2-d40e-4d57-9e40-c68d1786bc02)

**Comment by wangweitung** [comment]
```
version: '3'
services:
    hexo:
        container_name: hexo
        image: bloodstar/hexo:latest
#        hostname: hexo
        ports:
          - 7300:4000
        volumes:
          - ./file:/app
        #env_file:
        #  - .env  # 部分公用环境变量放到这里，以是的多个docker之间共享环境变量
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Shanghai
          - GIT_USER="123"
          - GIT_EMAIL="123@gmail.com"
          
          # 主要为了内部npm网络访问顺利
          # - HTTP_PROXY=http://192.168.0.100:1089
          # - HTTPS_PROXY=http://192.168.0.100:1089
        restart: always
        labels:
          - "com.centurylinklabs.watchtower.enable=true"
#        network_mode: bridge

```
